package com.demo.domain.model;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-06-12 13:21:10
 * @Table t_role_resource
*/
public class RoleResourceKey {
    /**
     * 角色ID: role_id
     * 
     * @mbg.generated 2019-06-12 13:21:10
     */
    private Integer roleId;

    /**
     * 资源ID: resource_id
     * 
     * @mbg.generated 2019-06-12 13:21:10
     */
    private Integer resourceId;

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Integer getResourceId() {
        return resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
}