package com.demo.domain.model;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author dell
 * @Date @mbg.generated 2018-17-46 05:46:56
 * @Table t_role_resource
*/
public class RoleResourceKey {
    /**
     * 角色ID: role_id
     * 
     * @mbg.generated 2018-17-46 05:46:56
      */
    private Integer roleId;

    /**
     * 资源ID: resource_id
     * 
     * @mbg.generated 2018-17-46 05:46:56
      */
    private Integer resourceId;

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Integer getResourceId() {
        return resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
}