package com.demo.domain.model;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author dell
 * @Date @mbg.generated 2018-17-46 05:46:56
 * @Table t_user_role
*/
public class UserRole extends UserRoleKey {
}