package com.demo.domain.model;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-05-14 14:38:31
 * @Table t_user_role
*/
public class UserRoleKey {
    /**
     * 用户ID: user_id
     * 
     * @mbg.generated 2019-05-14 14:38:31
      */
    private Integer userId;

    /**
     * 角色ID: role_id
     * 
     * @mbg.generated 2019-05-14 14:38:31
      */
    private Integer roleId;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}