package com.demo.domain.model;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author dell
 * @Date @mbg.generated 2018-17-46 05:46:56
 * @Table t_user_role
*/
public class UserRoleKey {
    /**
     * 用户ID: user_id
     * 
     * @mbg.generated 2018-17-46 05:46:56
      */
    private Integer userId;

    /**
     * 角色ID: role_id
     * 
     * @mbg.generated 2018-17-46 05:46:56
      */
    private Integer roleId;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}