package com.demo.dao;

import com.demo.compents.base.clazz.BaseDao;
import com.demo.domain.model.Resource;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @Description Automatically generated by MBG.
 * @Author dell
 * @Date 2018-16-41 04:41:27
 * @mbg.generated 2018-16-41 04:41:27
 */
@Repository
public interface ResourceDao extends BaseDao<Resource, Integer> {
    List<Resource> selectResourceListByRoleIds(@Param("roleIdList") List<Integer> roleIdList);

    List<Resource> selectResourceListByRoleIdsAndType(@Param("roleIdList") List<Integer> roleIdList, @Param("type") Integer type);
}