package com.demo.dao;

import com.demo.dao.base.BaseDao;
import com.demo.domain.model.RoleResource;
import com.demo.domain.model.RoleResourceKey;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author dell
 * @Date 2018-16-41 04:41:27
 * @mbg.generated 2018-16-41 04:41:27
*/
@Repository
public interface RoleResourceDao extends BaseDao<RoleResource, RoleResourceKey> {
}