package com.demo.dao;

import com.demo.dao.base.BaseDao;
import com.demo.domain.model.Role;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @Description Automatically generated by MBG.
 * @Author dell
 * @Date 2018-16-41 04:41:27
 * @mbg.generated 2018-16-41 04:41:27
 */
@Repository
public interface RoleDao extends BaseDao<Role, Integer> {
    List<Role> selectRoleListByUserId(@Param("userId") Integer userId);
}