package com.demo.dao;

import com.demo.compents.base.clazz.BaseDao;
import com.demo.domain.model.User;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author dell
 * @Date 2018-16-41 04:41:27
 * @mbg.generated 2018-16-41 04:41:27
 */
@Repository
public interface UserDao extends BaseDao<User, Integer> {
}